os: Visual Studio 2019

environment:
    PYTHON: "C:\Python37"

    matrix:

        - PROFILE:  msvc-d-shared
        - PROFILE:  msvc-r-static

install:
  - git clone https://github.com/TimSimpson/ci-land.git ci
  - cd ci
  - git checkout 609f4f928e53ae07749011f6d4d3305ea8300e9d
  - cd ..
  - ci\cpp\conan\appveyor\install.bat

build_script:
  - ci\cpp\conan\appveyor\run.bat %PROFILE%
